using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Card = System.Tuple<DroPoker.Suit, DroPoker.Dignity>;
    
namespace DroPoker
{
    static class CombinationArrayClass
    {
        public static Card[][] RoyalFlush = new Card[][]
        {
            new Card [] { Tuple.Create(Suit.Club, Dignity.Ten),
                          Tuple.Create(Suit.Club, Dignity.Jack),
                          Tuple.Create(Suit.Club, Dignity.Queen),
                          Tuple.Create(Suit.Club, Dignity.King),
                          Tuple.Create(Suit.Club, Dignity.Ace)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Ten),
                          Tuple.Create(Suit.Diamond, Dignity.Jack),
                          Tuple.Create(Suit.Diamond, Dignity.Queen),
                          Tuple.Create(Suit.Diamond, Dignity.King),
                          Tuple.Create(Suit.Diamond, Dignity.Ace)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Ten),
                          Tuple.Create(Suit.Heart, Dignity.Jack),
                          Tuple.Create(Suit.Heart, Dignity.Queen),
                          Tuple.Create(Suit.Heart, Dignity.King),
                          Tuple.Create(Suit.Heart, Dignity.Ace)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Ten),
                          Tuple.Create(Suit.Spade, Dignity.Jack),
                          Tuple.Create(Suit.Spade, Dignity.Queen),
                          Tuple.Create(Suit.Spade, Dignity.King),
                          Tuple.Create(Suit.Spade, Dignity.Ace)},
        };

        public static Card[][] StraightFlush = new Card[][]
        {
            new Card [] { Tuple.Create(Suit.Club, Dignity.Two), 
                          Tuple.Create(Suit.Club, Dignity.Three), 
                          Tuple.Create(Suit.Club, Dignity.Four), 
                          Tuple.Create(Suit.Club, Dignity.Five), 
                          Tuple.Create(Suit.Club, Dignity.Six)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Three),
                          Tuple.Create(Suit.Club, Dignity.Four),
                          Tuple.Create(Suit.Club, Dignity.Five),
                          Tuple.Create(Suit.Club, Dignity.Six),
                          Tuple.Create(Suit.Club, Dignity.Seven)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Four),
                          Tuple.Create(Suit.Club, Dignity.Five),
                          Tuple.Create(Suit.Club, Dignity.Six),
                          Tuple.Create(Suit.Club, Dignity.Seven),
                          Tuple.Create(Suit.Club, Dignity.Eight)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Five),
                          Tuple.Create(Suit.Club, Dignity.Six),
                          Tuple.Create(Suit.Club, Dignity.Seven),
                          Tuple.Create(Suit.Club, Dignity.Eight),
                          Tuple.Create(Suit.Club, Dignity.Nine)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Six),
                          Tuple.Create(Suit.Club, Dignity.Seven),
                          Tuple.Create(Suit.Club, Dignity.Eight),
                          Tuple.Create(Suit.Club, Dignity.Nine),
                          Tuple.Create(Suit.Club, Dignity.Ten)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Seven),
                          Tuple.Create(Suit.Club, Dignity.Eight),
                          Tuple.Create(Suit.Club, Dignity.Nine),
                          Tuple.Create(Suit.Club, Dignity.Ten),
                          Tuple.Create(Suit.Club, Dignity.Jack)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Eight),
                          Tuple.Create(Suit.Club, Dignity.Nine),
                          Tuple.Create(Suit.Club, Dignity.Ten),
                          Tuple.Create(Suit.Club, Dignity.Jack),
                          Tuple.Create(Suit.Club, Dignity.Queen)},
            new Card [] { Tuple.Create(Suit.Club, Dignity.Nine),
                          Tuple.Create(Suit.Club, Dignity.Ten),
                          Tuple.Create(Suit.Club, Dignity.Jack),
                          Tuple.Create(Suit.Club, Dignity.Queen),
                          Tuple.Create(Suit.Club, Dignity.King)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Two),
                          Tuple.Create(Suit.Spade, Dignity.Three),
                          Tuple.Create(Suit.Spade, Dignity.Four),
                          Tuple.Create(Suit.Spade, Dignity.Five),
                          Tuple.Create(Suit.Spade, Dignity.Six)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Three),
                          Tuple.Create(Suit.Spade, Dignity.Four),
                          Tuple.Create(Suit.Spade, Dignity.Five),
                          Tuple.Create(Suit.Spade, Dignity.Six),
                          Tuple.Create(Suit.Spade, Dignity.Seven)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Four),
                          Tuple.Create(Suit.Spade, Dignity.Five),
                          Tuple.Create(Suit.Spade, Dignity.Six),
                          Tuple.Create(Suit.Spade, Dignity.Seven),
                          Tuple.Create(Suit.Spade, Dignity.Eight)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Five),
                          Tuple.Create(Suit.Spade, Dignity.Six),
                          Tuple.Create(Suit.Spade, Dignity.Seven),
                          Tuple.Create(Suit.Spade, Dignity.Eight),
                          Tuple.Create(Suit.Spade, Dignity.Nine)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Six),
                          Tuple.Create(Suit.Spade, Dignity.Seven),
                          Tuple.Create(Suit.Spade, Dignity.Eight),
                          Tuple.Create(Suit.Spade, Dignity.Nine),
                          Tuple.Create(Suit.Spade, Dignity.Ten)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Seven),
                          Tuple.Create(Suit.Spade, Dignity.Eight),
                          Tuple.Create(Suit.Spade, Dignity.Nine),
                          Tuple.Create(Suit.Spade, Dignity.Ten),
                          Tuple.Create(Suit.Spade, Dignity.Jack)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Eight),
                          Tuple.Create(Suit.Spade, Dignity.Nine),
                          Tuple.Create(Suit.Spade, Dignity.Ten),
                          Tuple.Create(Suit.Spade, Dignity.Jack),
                          Tuple.Create(Suit.Spade, Dignity.Queen)},
            new Card [] { Tuple.Create(Suit.Spade, Dignity.Nine),
                          Tuple.Create(Suit.Spade, Dignity.Ten),
                          Tuple.Create(Suit.Spade, Dignity.Jack),
                          Tuple.Create(Suit.Spade, Dignity.Queen),
                          Tuple.Create(Suit.Spade, Dignity.King)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Two),
                          Tuple.Create(Suit.Heart, Dignity.Three),
                          Tuple.Create(Suit.Heart, Dignity.Four),
                          Tuple.Create(Suit.Heart, Dignity.Five),
                          Tuple.Create(Suit.Heart, Dignity.Six)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Three),
                          Tuple.Create(Suit.Heart, Dignity.Four),
                          Tuple.Create(Suit.Heart, Dignity.Five),
                          Tuple.Create(Suit.Heart, Dignity.Six),
                          Tuple.Create(Suit.Heart, Dignity.Seven)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Four),
                          Tuple.Create(Suit.Heart, Dignity.Five),
                          Tuple.Create(Suit.Heart, Dignity.Six),
                          Tuple.Create(Suit.Heart, Dignity.Seven),
                          Tuple.Create(Suit.Heart, Dignity.Eight)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Five),
                          Tuple.Create(Suit.Heart, Dignity.Six),
                          Tuple.Create(Suit.Heart, Dignity.Seven),
                          Tuple.Create(Suit.Heart, Dignity.Eight),
                          Tuple.Create(Suit.Heart, Dignity.Nine)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Six),
                          Tuple.Create(Suit.Heart, Dignity.Seven),
                          Tuple.Create(Suit.Heart, Dignity.Eight),
                          Tuple.Create(Suit.Heart, Dignity.Nine),
                          Tuple.Create(Suit.Heart, Dignity.Ten)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Seven),
                          Tuple.Create(Suit.Heart, Dignity.Eight),
                          Tuple.Create(Suit.Heart, Dignity.Nine),
                          Tuple.Create(Suit.Heart, Dignity.Ten),
                          Tuple.Create(Suit.Heart, Dignity.Jack)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Eight),
                          Tuple.Create(Suit.Heart, Dignity.Nine),
                          Tuple.Create(Suit.Heart, Dignity.Ten),
                          Tuple.Create(Suit.Heart, Dignity.Jack),
                          Tuple.Create(Suit.Heart, Dignity.Queen)},
            new Card [] { Tuple.Create(Suit.Heart, Dignity.Nine),
                          Tuple.Create(Suit.Heart, Dignity.Ten),
                          Tuple.Create(Suit.Heart, Dignity.Jack),
                          Tuple.Create(Suit.Heart, Dignity.Queen),
                          Tuple.Create(Suit.Heart, Dignity.King)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Two),
                          Tuple.Create(Suit.Diamond, Dignity.Three),
                          Tuple.Create(Suit.Diamond, Dignity.Four),
                          Tuple.Create(Suit.Diamond, Dignity.Five),
                          Tuple.Create(Suit.Diamond, Dignity.Six)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Three),
                          Tuple.Create(Suit.Diamond, Dignity.Four),
                          Tuple.Create(Suit.Diamond, Dignity.Five),
                          Tuple.Create(Suit.Diamond, Dignity.Six),
                          Tuple.Create(Suit.Diamond, Dignity.Seven)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Four),
                          Tuple.Create(Suit.Diamond, Dignity.Five),
                          Tuple.Create(Suit.Diamond, Dignity.Six),
                          Tuple.Create(Suit.Diamond, Dignity.Seven),
                          Tuple.Create(Suit.Diamond, Dignity.Eight)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Five),
                          Tuple.Create(Suit.Diamond, Dignity.Six),
                          Tuple.Create(Suit.Diamond, Dignity.Seven),
                          Tuple.Create(Suit.Diamond, Dignity.Eight),
                          Tuple.Create(Suit.Diamond, Dignity.Nine)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Six),
                          Tuple.Create(Suit.Diamond, Dignity.Seven),
                          Tuple.Create(Suit.Diamond, Dignity.Eight),
                          Tuple.Create(Suit.Diamond, Dignity.Nine),
                          Tuple.Create(Suit.Diamond, Dignity.Ten)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Seven),
                          Tuple.Create(Suit.Diamond, Dignity.Eight),
                          Tuple.Create(Suit.Diamond, Dignity.Nine),
                          Tuple.Create(Suit.Diamond, Dignity.Ten),
                          Tuple.Create(Suit.Diamond, Dignity.Jack)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Eight),
                          Tuple.Create(Suit.Diamond, Dignity.Nine),
                          Tuple.Create(Suit.Diamond, Dignity.Ten),
                          Tuple.Create(Suit.Diamond, Dignity.Jack),
                          Tuple.Create(Suit.Diamond, Dignity.Queen)},
            new Card [] { Tuple.Create(Suit.Diamond, Dignity.Nine),
                          Tuple.Create(Suit.Diamond, Dignity.Ten),
                          Tuple.Create(Suit.Diamond, Dignity.Jack),
                          Tuple.Create(Suit.Diamond, Dignity.Queen),
                          Tuple.Create(Suit.Diamond, Dignity.King)},
        };
    }
}
